import os


AWS_KEY = "VOCAREUM_AWS_KEY"
AWS_SECRET = "VOCAREUM_AWS_SECRET"
AWS_SESSION = "VOCAREUM_AWS_SESSION_TOKEN"
S3_BUCKET = "bucketaulainfraestrutura"
SECRET_KEY = os.urandom(32)
DEBUG = False
PORT = 5000
